### ISSUE TITLE
Operator needs to be installable via the marketplace

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#14]
**Story**

As a Rancher Operator,
I want to be able to install Rancher turtles via the marketplace
So that i have a standard way to install it

**Description**
This means packaing the operator as a Helm chart. Initially we will publish it to our own helm repository but ultimately this will need to be published in the main Rancher charts repo.

**Comment by alexander-demicev** [comment]
For the first iteration current github repo can be used as a helm chart repository as it's done with capi operator.
