### ISSUE TITLE
Validate getting started guide

### ISSUE THREAD

**Issue by salasberryfin** [rancher-sandbox/rancher-turtles#159]
### What would you like to be added (User Story)?

As a user I need to be able to install Rancher Turtles following the [getting started guide](https://docs.rancher-turtles.com/docs/category/getting-started)

### Label(s) to be applied

**Comment by salasberryfin** [comment]
The following PR contains a few updates to the docs: https://github.com/rancher-sandbox/rancher-turtles-docs/pull/35

**Comment by richardcase** [comment]
The docs PR has merged so this can be closed
