### ISSUE TITLE
Ensure CAPI Operator is installed

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#18]
**Story**

As a rancher operator,
I want to ensure the CAPI operator is installed when i install rancher turtles
So that i get CAPI and a **default** set of providers installed.

**Description**

We are going to rely on the [CAPI Operator](https://github.com/kubernetes-sigs/cluster-api-operator) to handle the install of CAPI and providers. We are also going to provider a "default" configuration. 

**Tasks**

- [x] Install the operator automatically (#91)
- [ ] Define if we want a core set of providers installed automatically

**Comment by alexander-demicev** [comment]
We need an issue for identifying a list of `default` providers, it should include both infrastructure and bootstrap. Do we want a mechanism to prevent users from deploying providers we don't support or hide it behind some feature flag?

**Comment by richardcase** [comment]
Agree on the list of default providers we want to enable when we install. I think this will be drive by product.... @davidstauffer .

We'll want to allow users to enable/disable providers like we currently do in Rancher. We have this issue in the UI: https://github.com/rancher-sandbox/rancher-turtles-ui/issues/5

**Comment by richardcase** [comment]
This can be closed as #91 is merged and we will only install the core provider initially
