### ISSUE TITLE
[E2E] Add test that covers installer Rancher being installed with CAPI disabled

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#193]
With #190 we are changing the tests so that Rancher is installed first with the "embedded CAPI" feature flag enabled and then disabling it before installing Rancher Turtles.

We need to have a test that covers this scenario:

- Rancher installed with the "embedded CAPI" feature flag disabled from install time
- Rancher Turtles installed
- Cluster created.

**Comment by salasberryfin** [comment]
Can we consider this as done after merging #178? If not, what is still missing?
