### ISSUE TITLE
Nightly e2e tests are failing

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#198]
### What steps did you take and what happened?

The nightly e2e tsts have been failing for a while now. For example:
https://github.com/rancher-sandbox/rancher-turtles/actions/runs/6480256714

### What did you expect to happen?

We need the e2e to be green and passing. to give confidence in out work.

### Label(s) to be applied

/kind bug

**Comment by richardcase** [comment]
The tests are still failing when being run from GitHub.

**Comment by salasberryfin** [comment]
Will switch to focusing on having the e2e tests running in a prow cluster.
