### ISSUE TITLE
Create and package UI extension

### ISSUE THREAD

**Issue by salasberryfin** [rancher-sandbox/rancher-turtles#20]
#### Story

As a user I can discover and install the Rancher CAPI extension from the UI.

#### Description

Rancher extensions are enabled from the Rancher UI which installs a Helm Chart and allows the user to use the extension in Rancher clusters.

- [ ] The chart will be defined in [rancher/ui-plugin-charts](https://github.com/rancher/ui-plugin-charts) and we can use existing extensions, such as Kubewarden, as a reference.
- [ ] Package UI extension: generate [JS package](https://github.com/rancher/ui-plugin-charts/tree/main/extensions/kubewarden/1.0.6/plugin)

#### Preliminary investigation

- How to build UI extension: scaffolding, docs, tools, etc.
- Structure: is it equivalent to other existing extensions?

**Comment by furkatgofurov7** [comment]
Moved it to https://github.com/rancher-sandbox/rancher-turtles-ui/issues/6, closing.
