### ISSUE TITLE
Create and package operator extension - Backend

### ISSUE THREAD

**Issue by salasberryfin** [rancher-sandbox/rancher-turtles#21]
#### Story

As a user I can install the Rancher CAPI extension and use it to provision my Rancher clusters.

This backend needs to be integrated with Fleet to make "all Rancher CAPI" GitOps friendly.

#### Description

The Rancher UI extension is backed by the backend operator code that implements the logic to use CAPI with Rancher.

During development, we'll be using custom repositories for the backend operator code. It can be configured from Rancher UI -> Continuous Delivery -> Git Repos -> Add Repo.

#### Preliminary investigation

Validate backend operator workflow:
- Rancher user communicates with Rancher Manager.
- Rancher Manager communicates with CAPI extension.
- The logic of communication between Rancher and CAPI is the core backend operator.

What do we need to integrate this with Fleet?

- [x] #81 
- [x] #117

**Comment by richardcase** [comment]
Initially we will publish into GHCR and then we will have discussion about an alternative location (i.e. with EIO).

**Comment by richardcase** [comment]
Needs to be installable via Rancher, so packaged as a Helm chart (with annotations/labels) and then we can add the repo to Rancher

**Comment by richardcase** [comment]
This is now complete, so closing
