### ISSUE TITLE
Rancher turtles fails to install via helm

### ISSUE THREAD

**Issue by Daemonslayer2048** [rancher-sandbox/rancher-turtles#377]
### What steps did you take and what happened?

Setup a fresh kubernetes cluster (I used RKE2 1.25.4), then follow the steps outlined below. According to the instructions a user is expected to install capi first then install turtles, however if you do this you will end up with the helm charts both attempting to create a resource `addonproviders.operator.cluster.x-k8s.io` and this causes the turtles helm chart to error out. 

__Install cert-manager:__
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
helm upgrade --install cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --wait \
    --version v1.11.0
```

__Install Rancher:__
```
kubectl create namespace cattle-system
helm upgrade --install rancher rancher-latest/rancher \
    --version v2.8.1 \            
    --namespace cattle-system \
    --values ./Kubernetes/helm/rancher-chart.yaml
```

__Install CAPI:__
```
kubectl apply -f ./Kubernetes/Temp/topology.yaml
helm upgrade --install capi-operator capi-operator/cluster-api-operator \
     --create-namespace -n capi-operator-system \
     --set infrastructure=docker:v1.4.6 \
     --set core=cluster-api:v1.4.6 \
     --set cert-manager.enabled=false 
```

__topology.yaml:__  
Referenced in the command above.
```
---
apiVersion: v1
kind: Secret
metadata:
  name: variables
  namespace: default
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_CLUSTER_RESOURCE_SET: "true"
```

__Install Turtles:__  
```
helm upgrade --install rancher-turtles turtles/rancher-turtles \
    --set cluster-api-operator.cert-manager.enabled=false \
    -n rancher-turtles-system \
    --dependency-update \
    --create-namespace
```

### What did you expect to happen?

I expected turtles to install successfully. 

### Rancher Turtles version

latest

### Anything else you would like to add?

Log:  
```
❯ helm upgrade --install rancher-turtles turtles/rancher-turtles \
                --set cluster-api-operator.cert-manager.enabled=false \
                -n rancher-turtles-system \
                --dependency-update \
                --create-namespace
Release "rancher-turtles" does not exist. Installing it now.
Error: Unable to continue with install: CustomResourceDefinition "addonproviders.operator.cluster.x-k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "rancher-turtles": current value is "capi-operator"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "rancher-turtles-system": current value is "capi-operator-system"
```

### Label(s) to be applied

/kind bug

**Comment by salasberryfin** [comment]
Hi @Daemonslayer2048, thanks for reporting this.

Looks like the Rancher Turtles docs are not very clear on how to install Turtles after installing CAPI Operator (I've created [this issue](https://github.com/rancher-sandbox/rancher-turtles-docs/issues/60) to improve this). The default behavior is to install CAPI Operator together with Rancher Turtles and, if CAPI Operator is already installed, you should add the following `--set cluster-api-operator.enabled=false` to the `helm install` command. This way, Rancher Turtles won't try to install CAPI Operator again, which would conflict with the existing installation.

An example command would like this:
```
helm install rancher-turtles turtles/rancher-turtles --version v0.4.0
    -n rancher-turtles-system
    --set cluster-api-operator.enabled=false
    --set cluster-api-operator.cluster-api.enabled=false
    --create-namespace --wait
    --dependency-update
```

You can read about this particular case [here](https://docs.rancher-turtles.com/docs/getting-started/install_turtles_operator#install-rancher-turtles-operator-without-cluster-api-operator-as-a-helm-dependency).

Could you confirm if passing this flag solves the issue?

**Comment by salasberryfin** [comment]
The docs have been updated to be more specific on how to install Rancher Turtles after installing CAPI Operator (see [here](https://docs.rancher-turtles.com/docs/getting-started/install_capi_operator#install-manually-with-helm-alternative)). We will consider this as addressed due to inactivity. If this problem still persists or you happen to have any other issues, we'll be happy to investigate it.
