### ISSUE TITLE
Enabling digital ocean provider fails

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#386]
### What steps did you take and what happened?

When trying to enable the digital ocean CAPI provider referencing a Rancher Cloud Credential we are seeing this error:

```
E0216 14:03:50.520691       1 secret_mapper_sync.go:279]  "msg"="failed to map credential keys" "error"="key not  │
│ found: digitaloceancredentialConfig-accessToken" "CAPIProvider"={"name":"digitalocean","namespace":"capdo-system" │
│ } "controller"="capiprovider" "controllerGroup"="turtles-capi.cattle.io" "controllerKind"="CAPIProvider" "name"=" │
│ digitalocean" "namespace"="capdo-system" "reconcileID"="36c806a1-6231-4121-9cb5-bdedc6315c6b"                     │
│ E0216 14:03:50.520739       1 controller.go:329]  "msg"="Reconciler error" "error"="unable to locate rancher secr │
│ et with name cattle-global-data:cc-7zfpj for provider digitalocean" "CAPIProvider"={"name":"digitalocean","namesp │
│ ace":"capdo-system"} "controller"="capiprovider" "controllerGroup"="turtles-capi.cattle.io" "controllerKind"="CAP │
│ IProvider" "name"="digitalocean" "namespace"="capdo-system" "reconcileID"="36c806a1-6231-4121-9cb5-bdedc6315c6b"
```

### What did you expect to happen?

The expectation is the provider is installed and the credentials from the Rancher Cloud Credential are used when enabling the DO provider.

### How to reproduce it?

1. Setup Rancher Manager (tested with v2.8.2)
2. Install Rancher Turtles (tested with v0.5.0)
3. Create a DO cloud credential in Rancher manager
4. Create a namespace:

```bash
kubectl create ns capdo-system
```

6. Apply the following yaml to enable the DO CAPI provider

> **You will need to change the name of the cloud credential from cc-7zfpj

```yaml
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: digitalocean
  namespace: capdo-system
spec:
  # configSecret:
  #   name: digitalocean-credentials-wnmr7
  credentials:
    rancherCloudCredential: cattle-global-data:cc-7zfpj
  features:
    clusterResourceSet: true
    clusterTopology: true
    machinePool: true
  name: digitalocean
  type: infrastructure
  variables: {}
```

### Rancher Turtles version

v0.5.0

### Label(s) to be applied

/kind bug

**Comment by Danil-Grigorev** [comment]
I suspect this is an incorrect usage of the CAPIProvider rancherCloudCredential field. It is supposed to have a name of the secret as it is displayed in the UI. The lookup is done by name annotation. There is no way UI user will know this `cattle-global-data:cc-7zfpj`. Unless that's the name of the created secret set by user?

**Comment by richardcase** [comment]
@Danil-Grigorev - you are correct, the `cattle-global-data:cc-7zfp` is the namespace and name of the secret that contains the cloud credential details and not the **display name**.

So it looks like there was some ambiguity around **name** and what whats passed isn't the display name. Lets wait for confirmation before making any changes.

**Comment by richardcase** [comment]
Confirmed, we need to change the logic so it looks up the cloud credential secret based on the `namespace:name` supplied and not using the display name.

**Comment by richardcase** [comment]
I think we should add a new field to **CAPIProvider** so that we can support the following:

- Looking up the credential based on the display name (current behavior)
- Looking up the credential based on a field that contains `namespace:name`

The webhook should not allow both to be set. Having the 2 fields will allow us to support the UI and also a more friendly lookup based on display name for GitOps type scenarios.
