### ISSUE TITLE
Rancher Turtles doesn't remove cleanly

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#409]
### What steps did you take and what happened?

For an existing Rancher Manager cluster that has clusters created via the existing provisioning mechanism if you install Rancher Turtles and then later uninstall then you get errors in cluster management.

Rancher Turtles does not uninstall cleanly, it can leave behind CAPI deployments and webhooks.

### What did you expect to happen?

I'd expect the following:
- Rancher Turtles should uninstall cleanly
- There should be documentation to restore any features that have been disabled
- To be able to continue to manage the clusters already created via Rancher Manager

### How to reproduce it?

- Install Rancher 2.8.2...standard (i.e. with no feature flags disabled)
- Create AWS based RKE2 cluster
- Create EKS cluster
- Wait for clusters to be **Active**
- Disable embedded CAPI by applying:

```yaml
apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  name: embedded-cluster-api
spec:
  value: false
```
- Cluster management screen will probably show errors
- Got to local cluster and install Rancher Turtles
	- Using default options
	- Wait for install to succeed
- Go to cluster management screen
	- Wait for clusters to all become **active** again
- Go to local cluster in Rancher Manager and uninstall Rancher Turtles
	- Watch which pods get deleted (sometimes CAPI pods get left behind)
	- Check the cluster management screen and wait for 5 - 10 mins to see if any of the clusters got into an **Error** state
- Re-enable embedded embedded CAPI manually by applying:

```yaml
apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  name: embedded-cluster-api
spec:
  value: true
```

- Wait for the rancher capi controller manager to be installed again
- Go to cluster management in Rancher Manager
- Wait for a while to see if the clusters in **error** become **active**
- Cluster remains in error:
  - Check there are no deployments left over from Turtles / CAPI operator
    - Observed once that the core CAPI deployment wasn't cleaned up
  - Check there are no mutating or validating webhooks left over
    - Observed that the webhooks aren't cleaned up (kubeadm and core capi)
- Manually delete the webhook (and deployment) resources left behind my RT/CAPI Operator (if any)
- Wait to see if clusters go **active**

### Rancher Turtles version

v0.5.0

### Anything else you would like to add?

I have observed the following:
- mutating and validation webhooks left behind by Rancher Turtles/CAPI Operator
- some times the core capi controller-manager deployment left behind

### Label(s) to be applied

/kind bug

**Comment by furkatgofurov7** [comment]
I was able to repro it with exact above steps. The only difference I saw was `capi kubeadm-controller-manager` deployment was left behind in my setup.
