### ISSUE TITLE
Implement credentials mapping from Rancher to CAPI

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#5]
**Story**

As a rancher operator,
I want to use Rancher Manager cloud credentials with CAPI,
So that I don't have to enter credentials twice in the UI.

**Description**
We would like to prove out credentials mapping from Rancher cloud credentials to CAPI credentials.

We'd need to watch for AWS cloud-credentials in the Rancher manager cluster and then create the relevant CAPI credential type for the provider.

For example, for AWS credentials we would create an instance of `AWSClusterStaticIdentity`.

**Unanswered Questions**
Do we do this ahead of time? Or at the point of creating the cluster?

**Comment by alexander-demicev** [comment]
The feature can be implemented in a separate controller and has to be addressed after we leverage the usage of CAPI Operator, this way we can understand what infra provider was installed and in which namespace.

**Comment by richardcase** [comment]
This is going to be covered by #286

**Comment by richardcase** [comment]
After discussions with @alexander-demicev and @Danil-Grigorev we will map the secrets when a provider is enabled.

The confluence page has more details
