### ISSUE TITLE
Testing Doc for QA

### ISSUE THREAD

**Issue by cpinjani** [rancher-sandbox/rancher-turtles#72]
### What would you like to be added (User Story)?

As a QA, I would like to have a Design Doc for deriving testing scenarios

### Detailed Description

Design Doc template: https://confluence.suse.com/display/CECO/Design+Doc+for+QA?src=contextnavpagetreemode

**Comment by richardcase** [comment]
Some examples courtesy of @cpinjani 💯 

https://confluence.suse.com/display/HARV/VM+backup+and+restore
https://confluence.suse.com/display/EN/Design%3A+Norman+to+Webhook+migration
https://confluence.suse.com/display/RMI/Token+Hashing+-+Design+Doc

**Comment by juadk** [comment]
It is a bit outdated but this is what we use for Elemental:
https://confluence.suse.com/display/CECO/Frontend+Testing+Plan

**Comment by richardcase** [comment]
Documented in [Google docs](https://docs.google.com/document/d/1MMt4yDJzH4hDsRGHyaGJ8Lpiujuevml9U5w3DjC2GQs/edit?usp=sharing).

**Comment by cpinjani** [comment]
LGTM, moved the testing plan to QASE https://app.qase.io/project/HIGHLANDER?suite=38
Will be adding the subsequent Backend and UI test scenarios in QASE test suite
