### ISSUE TITLE
Gaps in rancher cluster deletion process

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher-sandbox/rancher-turtles#86]
Currently there are several issues with implementation of deletion strategy for the rancher cluster.

1. `imported=true` annotation is being set conditionally based on the fact it should also be present on the rancher cluster. It [shouldn’t](https://github.com/rancher-sandbox/rancher-turtles/pull/85/files#diff-7c0fda45174e6cff5feacf49979ba7f3f56d797cb698ce3a8f9dc4f654124ee7R18), the behavior supposed to be automatic upon cluster deletion.
2. Events coming from updates of the rancher cluster are not propagated to the CAPI cluster due to incorrect name mapping between the two.
3. Controller-runtime mapper methods do not support predicate filtering logic on enqueued requests, it triggers reconciliation on the resource directly by enqueuing the `NamespaceName` of the object and passing it into the [work queue](https://github.com/kubernetes-sigs/controller-runtime/blob/c20ea143a236a34fb331e6c04820b75aac444e7d/pkg/internal/controller/controller.go#L249). Which causes the following race condition:
    - Rancher cluster is getting deleted. This generates a mapped reconcile request to the CAPI cluster, which triggers a reconcile loop without passing predicate logic for the enqueued CAPI cluster. Rancher cluster has deletion timestamp, so the CAPI cluster is annotated and nothing else happens.
    - At some point Rancher cluster is finally removed, which, again, triggers reconcile on CAPI cluster and it follows to the reconcileNormal scenario. The Rancher cluster is re-created again and is visible in UI.

**Comment by furkatgofurov7** [comment]
I think this can be closed
